package model;

// Generated May 9, 2015 4:50:58 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "Book", catalog = "library")
public class Book implements java.io.Serializable {

	private String bookNo;
	private String bookName;
	private String author;
	private String publishers;
	private String retrievalNo;
	private String bookNumber;
	private String remainingBookNumber;
	private Set<User> userHasBooks = new HashSet<User>(0);

	public Book() {
	}

	public Book(String bookNo, String bookName) {
		this.bookNo = bookNo;
		this.bookName = bookName;
	}

	public Book(String bookNo, String bookName, String author,
			String publishers, String retrievalNo, String bookNumber,
			String remainingBookNumber, Set userHasBooks) {
		this.bookNo = bookNo;
		this.bookName = bookName;
		this.author = author;
		this.publishers = publishers;
		this.retrievalNo = retrievalNo;
		this.bookNumber = bookNumber;
		this.remainingBookNumber = remainingBookNumber;
		this.userHasBooks = userHasBooks;
	}

	@Id
	@Column(name = "BookNo", unique = true, nullable = false, length = 10)
	@GeneratedValue(strategy = GenerationType.AUTO)  
	public String getBookNo() {
		return this.bookNo;
	}

	public void setBookNo(String bookNo) {
		this.bookNo = bookNo;
	}

	@Column(name = "BookName", nullable = false, length = 45)
	public String getBookName() {
		return this.bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	@Column(name = "Author", length = 45)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "Publishers", length = 45)
	public String getPublishers() {
		return this.publishers;
	}

	public void setPublishers(String publishers) {
		this.publishers = publishers;
	}

	@Column(name = "RetrievalNo", length = 45)
	public String getRetrievalNo() {
		return this.retrievalNo;
	}

	public void setRetrievalNo(String retrievalNo) {
		this.retrievalNo = retrievalNo;
	}

	@Column(name = "BookNumber", length = 45)
	public String getBookNumber() {
		return this.bookNumber;
	}

	public void setBookNumber(String bookNumber) {
		this.bookNumber = bookNumber;
	}

	@Column(name = "RemainingBookNumber", length = 45)
	public String getRemainingBookNumber() {
		return this.remainingBookNumber;
	}

	public void setRemainingBookNumber(String remainingBookNumber) {
		this.remainingBookNumber = remainingBookNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userNo")
	public Set<User> getUserHasBooks() {
		return this.userHasBooks;
	}

	public void setUserHasBooks(Set userHasBooks) {
		this.userHasBooks = userHasBooks;
	}

}
