package model;

// Generated May 9, 2015 4:50:58 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Staff generated by hbm2java
 */
@Entity
@Table(name = "Staff", catalog = "library")
public class Staff implements java.io.Serializable {

	private int staffNo;
	private String staffName;
	private String staffpassword;

	public Staff() {
	}

	public Staff(int staffNo, String staffName, String staffpassword) {
		this.staffNo = staffNo;
		this.staffName = staffName;
		this.staffpassword = staffpassword;
	}

	@Id
	@Column(name = "StaffNo", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO) 
	public int getStaffNo() {
		return this.staffNo;
	}

	public void setStaffNo(int staffNo) {
		this.staffNo = staffNo;
	}

	@Column(name = "StaffName", nullable = false, length = 45)
	public String getStaffName() {
		return this.staffName;
	}

	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}

	@Column(name = "Staffpassword", nullable = false, length = 10)
	public String getStaffpassword() {
		return this.staffpassword;
	}

	public void setStaffpassword(String staffpassword) {
		this.staffpassword = staffpassword;
	}

}
