package model;

// Generated May 9, 2015 4:50:58 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "User", catalog = "library")
public class User implements java.io.Serializable {

	private int userNo;
	private String userName;
	private String password;
	private Set<Book> userHasBooks = new HashSet<Book>(0);

	public User() {
	}

	public User(int userNo, String userName, String password) {
		this.userNo = userNo;
		this.userName = userName;
		this.password = password;
	}

	public User(int userNo, String userName, String password, Set userHasBooks) {
		this.userNo = userNo;
		this.userName = userName;
		this.password = password;
		this.userHasBooks = userHasBooks;
	}

	@Id
	@Column(name = "UserNo", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO)
	public int getUserNo() {
		return this.userNo;
	}

	public void setUserNo(int userNo) {
		this.userNo = userNo;
	}

	@Column(name = "UserName", unique = true, nullable = false, length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "Password", nullable = false, length = 10)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bookNo")
	public Set<Book> getUserHasBooks() {
		return this.userHasBooks;
	}

	public void setUserHasBooks(Set userHasBooks) {
		this.userHasBooks = userHasBooks;
	}

}
