package model;

// Generated May 12, 2015 12:53:28 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserHasBookId generated by hbm2java
 */
@Embeddable
public class UserHasBookId implements java.io.Serializable {

	private int userUserNo;
	private int bookBookNo;

	public UserHasBookId() {
	}

	public UserHasBookId(int userUserNo, int bookBookNo) {
		this.userUserNo = userUserNo;
		this.bookBookNo = bookBookNo;
	}

	@Column(name = "User_UserNo", nullable = false)
	public int getUserUserNo() {
		return this.userUserNo;
	}

	public void setUserUserNo(int userUserNo) {
		this.userUserNo = userUserNo;
	}

	@Column(name = "Book_BookNo", nullable = false)
	public int getBookBookNo() {
		return this.bookBookNo;
	}

	public void setBookBookNo(int bookBookNo) {
		this.bookBookNo = bookBookNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserHasBookId))
			return false;
		UserHasBookId castOther = (UserHasBookId) other;

		return (this.getUserUserNo() == castOther.getUserUserNo())
				&& (this.getBookBookNo() == castOther.getBookBookNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserUserNo();
		result = 37 * result + this.getBookBookNo();
		return result;
	}

}
