package model;

// Generated May 9, 2015 4:50:58 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserHasBook generated by hbm2java
 */
@Entity
@Table(name = "User_has_Book", catalog = "library")
public class UserHasBook implements java.io.Serializable {

	private UserHasBookId id;
	private User user;
	private Book book;
	private Date borrowDate;

	public UserHasBook() {
	}

	public UserHasBook(UserHasBookId id, User user, Book book) {
		this.id = id;
		this.user = user;
		this.book = book;
	}

	public UserHasBook(UserHasBookId id, User user, Book book, Date borrowDate) {
		this.id = id;
		this.user = user;
		this.book = book;
		this.borrowDate = borrowDate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userUserNo", column = @Column(name = "User_UserNo", nullable = false)),
			@AttributeOverride(name = "bookBookNo", column = @Column(name = "Book_BookNo", nullable = false, length = 10)) })
	public UserHasBookId getId() {
		return this.id;
	}

	public void setId(UserHasBookId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "User_UserNo", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Book_BookNo", nullable = false, insertable = false, updatable = false)
	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BorrowDate", length = 10)
	public Date getBorrowDate() {
		return this.borrowDate;
	}

	public void setBorrowDate(Date borrowDate) {
		this.borrowDate = borrowDate;
	}

}
